eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9094/eureka/

spring:
  application:
    name: demo-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    refresh:
      enabled: false
  main:
    allow-bean-definition-overriding: true
